package com.voteomatic.cryptography.core.zkp;

import java.io.Serializable;

/**
 * Marker interface for a generated Zero-Knowledge Proof. Concrete implementations will define the
 * specific data comprising the proof generated by a particular ZKP system (e.g., commitments,
 * challenges, responses). It extends Serializable to ensure all proof types can be serialized.
 */
public interface Proof extends Serializable {
  // Marker interface - no methods required at this base level.
  // Implementations will contain the actual proof data.
}
